postgres: &postgres
  adapter: postgresql
  username: <%= ENV['DBUSER'] || "pramati" %>
  password: <%= ENV['DBPASS'] || "pramati" %>
  encoding: UTF8

development:
  <<: *postgres
  database: video_portal1_development
  host: localhost

test:
  <<: *postgres
  database: video_portal1_test
  host: localhost

production:
  <<: *postgres
  database: video_portal1_production
  host: localhost
